import type { Policy, Claim, Customer, RiskAssessment, AgencyMetrics, ClaimsPipelineStage } from "./types";

export const demoCustomers: Customer[] = [
  {
    id: "cust_001",
    fullName: "Michael Chen",
    email: "m.chen@example.test",
    phone: "+1-415-555-0142",
    address: "847 Folsom St",
    city: "San Francisco",
    state: "CA",
    preferredCommunicationChannel: "customer_portal",
    tier: "platinum",
    activePolicies: 3,
    totalPremiumVolume: 12400,
    lifetimeValue: 68000,
    claimsHistory: 1,
    satisfactionScore: 94,
    joinedDate: "2018-03-15T00:00:00Z",
  },
  {
    id: "cust_002",
    fullName: "Sarah Okonkwo",
    email: "s.okonkwo@example.test",
    phone: "+1-312-555-0289",
    address: "210 Michigan Ave",
    city: "Chicago",
    state: "IL",
    preferredCommunicationChannel: "sms",
    tier: "gold",
    activePolicies: 2,
    totalPremiumVolume: 8600,
    lifetimeValue: 42000,
    claimsHistory: 2,
    satisfactionScore: 88,
    joinedDate: "2019-07-22T00:00:00Z",
  },
  {
    id: "cust_003",
    fullName: "David Nakamura",
    email: "d.nakamura@example.test",
    phone: "+1-212-555-0391",
    address: "450 Park Ave",
    city: "New York",
    state: "NY",
    preferredCommunicationChannel: "email",
    tier: "platinum",
    activePolicies: 4,
    totalPremiumVolume: 22800,
    lifetimeValue: 112000,
    claimsHistory: 0,
    satisfactionScore: 97,
    joinedDate: "2015-11-08T00:00:00Z",
  },
  {
    id: "cust_004",
    fullName: "Aisha Patel",
    email: "a.patel@example.test",
    phone: "+1-512-555-0447",
    address: "1223 S Congress Ave",
    city: "Austin",
    state: "TX",
    preferredCommunicationChannel: "sms",
    tier: "silver",
    activePolicies: 2,
    totalPremiumVolume: 5200,
    lifetimeValue: 18000,
    claimsHistory: 3,
    satisfactionScore: 72,
    joinedDate: "2021-01-14T00:00:00Z",
  },
  {
    id: "cust_005",
    fullName: "Robert Kowalski",
    email: "r.kowalski@example.test",
    phone: "+1-206-555-0512",
    address: "78 Pike St",
    city: "Seattle",
    state: "WA",
    preferredCommunicationChannel: "email",
    tier: "gold",
    activePolicies: 1,
    totalPremiumVolume: 9600,
    lifetimeValue: 31000,
    claimsHistory: 1,
    satisfactionScore: 85,
    joinedDate: "2020-06-03T00:00:00Z",
  },
  {
    id: "cust_006",
    fullName: "Elena Vasquez",
    email: "e.vasquez@example.test",
    phone: "+1-305-555-0678",
    address: "1400 Brickell Ave",
    city: "Miami",
    state: "FL",
    preferredCommunicationChannel: "phone",
    tier: "standard",
    activePolicies: 1,
    totalPremiumVolume: 3400,
    lifetimeValue: 8900,
    claimsHistory: 4,
    satisfactionScore: 65,
    joinedDate: "2022-09-30T00:00:00Z",
  },
  {
    id: "cust_007",
    fullName: "Thomas Berglund",
    email: "t.berglund@example.test",
    phone: "+1-617-555-0732",
    address: "300 Boylston St",
    city: "Boston",
    state: "MA",
    preferredCommunicationChannel: "customer_portal",
    tier: "platinum",
    activePolicies: 3,
    totalPremiumVolume: 15600,
    lifetimeValue: 85000,
    claimsHistory: 0,
    satisfactionScore: 96,
    joinedDate: "2016-04-19T00:00:00Z",
  },
  {
    id: "cust_008",
    fullName: "Priya Sharma",
    email: "p.sharma@example.test",
    phone: "+1-303-555-0845",
    address: "1601 Wewatta St",
    city: "Denver",
    state: "CO",
    preferredCommunicationChannel: "sms",
    tier: "silver",
    activePolicies: 2,
    totalPremiumVolume: 6100,
    lifetimeValue: 22000,
    claimsHistory: 1,
    satisfactionScore: 81,
    joinedDate: "2021-08-12T00:00:00Z",
  },
  {
    id: "cust_009",
    fullName: "James O'Brien",
    email: "j.obrien@example.test",
    phone: "+1-615-555-0963",
    address: "222 2nd Ave S",
    city: "Nashville",
    state: "TN",
    preferredCommunicationChannel: "phone",
    tier: "standard",
    activePolicies: 1,
    totalPremiumVolume: 2800,
    lifetimeValue: 6100,
    claimsHistory: 5,
    satisfactionScore: 58,
    joinedDate: "2023-02-20T00:00:00Z",
  },
  {
    id: "cust_010",
    fullName: "Fatima Al-Rashid",
    email: "f.alrashid@example.test",
    phone: "+1-702-555-0107",
    address: "3750 Las Vegas Blvd",
    city: "Las Vegas",
    state: "NV",
    preferredCommunicationChannel: "email",
    tier: "gold",
    activePolicies: 2,
    totalPremiumVolume: 7200,
    lifetimeValue: 34000,
    claimsHistory: 0,
    satisfactionScore: 91,
    joinedDate: "2020-12-05T00:00:00Z",
  },
];

export const demoPolicies: Policy[] = [
  {
    id: "pol_001",
    policyNumber: "AUTO-8821-SF",
    customerId: "cust_001",
    type: "auto",
    status: "active",
    coverageAmount: 300000,
    monthlyPremium: 245,
    annualPremium: 2940,
    deductible: 1000,
    startDate: "2025-11-01T00:00:00Z",
    endDate: "2026-10-31T00:00:00Z",
    aiRiskScore: 18,
    aiRiskLevel: "low",
    tags: ["tesla_model_3", "garaged", "clean_record"],
  },
  {
    id: "pol_002",
    policyNumber: "HOME-4492-SF",
    customerId: "cust_001",
    type: "home",
    status: "active",
    coverageAmount: 850000,
    monthlyPremium: 312,
    annualPremium: 3744,
    deductible: 2500,
    startDate: "2025-09-15T00:00:00Z",
    endDate: "2026-09-14T00:00:00Z",
    aiRiskScore: 22,
    aiRiskLevel: "low",
    tags: ["earthquake_zone", "sprinkler_system", "recent_roof"],
  },
  {
    id: "pol_003",
    policyNumber: "LIFE-7731-ML",
    customerId: "cust_003",
    type: "life",
    status: "active",
    coverageAmount: 2000000,
    monthlyPremium: 680,
    annualPremium: 8160,
    deductible: 0,
    startDate: "2024-06-01T00:00:00Z",
    endDate: "2044-05-31T00:00:00Z",
    aiRiskScore: 8,
    aiRiskLevel: "low",
    tags: ["term_20yr", "medical_cleared", "non_smoker"],
  },
  {
    id: "pol_004",
    policyNumber: "COMM-1209-CH",
    customerId: "cust_004",
    type: "commercial",
    status: "pending_renewal",
    coverageAmount: 5000000,
    monthlyPremium: 1800,
    annualPremium: 21600,
    deductible: 10000,
    startDate: "2025-07-01T00:00:00Z",
    endDate: "2026-06-30T00:00:00Z",
    aiRiskScore: 55,
    aiRiskLevel: "elevated",
    tags: ["restaurant", "liquor_liability", "claims_last_year"],
  },
  {
    id: "pol_005",
    policyNumber: "AUTO-6614-CH",
    customerId: "cust_002",
    type: "auto",
    status: "expiring",
    coverageAmount: 250000,
    monthlyPremium: 195,
    annualPremium: 2340,
    deductible: 500,
    startDate: "2025-08-01T00:00:00Z",
    endDate: "2026-07-31T00:00:00Z",
    aiRiskScore: 42,
    aiRiskLevel: "moderate",
    tags: ["honda_crv", "commuter", "recent_claim"],
  },
  {
    id: "pol_006",
    policyNumber: "HOME-5587-WA",
    customerId: "cust_005",
    type: "home",
    status: "active",
    coverageAmount: 1200000,
    monthlyPremium: 480,
    annualPremium: 5760,
    deductible: 5000,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2026-12-31T00:00:00Z",
    aiRiskScore: 35,
    aiRiskLevel: "moderate",
    tags: ["waterfront", "flood_zone", "elevated_foundation"],
  },
  {
    id: "pol_007",
    policyNumber: "COMM-3341-NY",
    customerId: "cust_003",
    type: "commercial",
    status: "active",
    coverageAmount: 8000000,
    monthlyPremium: 2800,
    annualPremium: 33600,
    deductible: 25000,
    startDate: "2025-04-01T00:00:00Z",
    endDate: "2026-03-31T00:00:00Z",
    aiRiskScore: 12,
    aiRiskLevel: "low",
    tags: ["office_building", "sprinkler_system", "security_24_7"],
  },
  {
    id: "pol_008",
    policyNumber: "AUTO-9903-LV",
    customerId: "cust_010",
    type: "auto",
    status: "active",
    coverageAmount: 200000,
    monthlyPremium: 160,
    annualPremium: 1920,
    deductible: 1000,
    startDate: "2026-02-15T00:00:00Z",
    endDate: "2027-02-14T00:00:00Z",
    aiRiskScore: 28,
    aiRiskLevel: "low",
    tags: ["toyota_camry", "low_mileage", "clean_record"],
  },
];

export const demoClaims: Claim[] = [
  {
    id: "clm_001",
    claimNumber: "CLM-2026-0842",
    policyId: "pol_005",
    customerId: "cust_002",
    type: "auto_collision",
    status: "new",
    amount: 12500,
    deductibleApplied: 500,
    payoutAmount: 0,
    reserveAmount: 12000,
    filedDate: "2026-06-08T09:15:00Z",
    lastUpdated: "2026-06-08T09:15:00Z",
    fnolChannel: "mobile_app",
    documentStatus: "complete",
    reviewGate: "adjuster_review",
    triageLane: "fast_attention",
    triageSignals: ["complete_evidence", "liability_review"],
    adverseActionNoticeRequired: false,
    governanceCheckpoint: {
      ownerRole: "adjuster",
      dueAt: "2026-06-09T17:00:00Z",
      nextAction: "Confirm liability decision and customer estimate match before first payout recommendation.",
    },
    communicationCheckpoint: {
      audience: "customer",
      channel: "sms",
      status: "scheduled",
      lastSentAt: "2026-06-08T10:05:00Z",
      nextDueAt: "2026-06-09T13:00:00Z",
      message: "Customer gets a next-day liability status update after the adjuster confirms the police citation and repair estimate alignment.",
    },
    complianceCheckpoint: {
      jurisdiction: "IL",
      obligation: "status_update",
      status: "due",
      dueAt: "2026-06-10T17:00:00Z",
      ruleReference: "Carrier-configured Illinois claims communication diary",
    },
    aiDecisionRationale: "Low fraud score with aligned dashcam and police details; adjuster verifies liability before payout recommendation.",
    evidenceAnchors: [
      { label: "Dashcam stills from insured vehicle", sourceType: "photos", receivedAt: "2026-06-08T09:45:00Z" },
      { label: "Police citation for other driver", sourceType: "police_report", receivedAt: "2026-06-08T12:10:00Z" },
    ],
    evidenceRequirements: [
      { label: "Dashcam stills from insured vehicle", status: "received", ownerRole: "adjuster" },
      { label: "Police citation for other driver", status: "received", ownerRole: "adjuster" },
      { label: "Initial repair estimate", status: "received", ownerRole: "adjuster" },
    ],
    aiFraudScore: 12,
    adjuster: "Maria Gonzalez",
    notes: "Rear-end collision at intersection. Dashcam footage available. Other party cited.",
  },
  {
    id: "clm_002",
    claimNumber: "CLM-2026-0781",
    policyId: "pol_006",
    customerId: "cust_005",
    type: "home_fire",
    status: "under_review",
    amount: 85000,
    deductibleApplied: 5000,
    payoutAmount: 0,
    reserveAmount: 95000,
    filedDate: "2026-05-22T14:30:00Z",
    lastUpdated: "2026-06-07T11:00:00Z",
    fnolChannel: "agent_portal",
    documentStatus: "pending_third_party",
    reviewGate: "supervisor_review",
    triageLane: "missing_information",
    triageSignals: ["third_party_dependency", "large_loss"],
    adverseActionNoticeRequired: false,
    governanceCheckpoint: {
      ownerRole: "third_party",
      dueAt: "2026-06-10T17:00:00Z",
      nextAction: "Collect the pending restoration estimate and reconcile fire department findings with the reserve before settlement review.",
    },
    communicationCheckpoint: {
      audience: "third_party",
      channel: "vendor_portal",
      status: "waiting_on_response",
      lastSentAt: "2026-06-07T11:20:00Z",
      nextDueAt: "2026-06-10T11:00:00Z",
      message: "Restoration vendor follow-up is tracked separately so the customer is not recontacted for a third-party estimate blocker.",
    },
    complianceCheckpoint: {
      jurisdiction: "WA",
      obligation: "status_update",
      status: "at_risk",
      dueAt: "2026-06-10T17:00:00Z",
      ruleReference: "Carrier-configured Washington claims communication diary",
    },
    aiDecisionRationale: "Large-loss fire claim remains pending until third-party restoration estimate and fire department findings reconcile with the reserve.",
    evidenceAnchors: [
      { label: "Fire department incident report", sourceType: "fire_report", receivedAt: "2026-05-23T10:20:00Z" },
      { label: "Restoration scope estimate pending carrier review", sourceType: "repair_estimate", receivedAt: "2026-06-07T10:15:00Z" },
    ],
    evidenceRequirements: [
      { label: "Fire department incident report", status: "received", ownerRole: "adjuster" },
      {
        label: "Restoration scope estimate",
        status: "pending_third_party",
        ownerRole: "third_party",
        dueAt: "2026-06-10T17:00:00Z",
      },
      {
        label: "Reserve reconciliation worksheet",
        status: "needs_adjuster_review",
        ownerRole: "supervisor",
        dueAt: "2026-06-11T17:00:00Z",
      },
    ],
    aiFraudScore: 18,
    adjuster: "Robert Kim",
    notes: "Kitchen fire with smoke damage throughout first floor. Fire dept report received. Restoration estimate pending.",
  },
  {
    id: "clm_003",
    claimNumber: "CLM-2026-0654",
    policyId: "pol_001",
    customerId: "cust_001",
    type: "auto_theft",
    status: "approved",
    amount: 42000,
    deductibleApplied: 1000,
    payoutAmount: 41000,
    reserveAmount: 41000,
    filedDate: "2026-04-30T08:00:00Z",
    lastUpdated: "2026-06-01T16:30:00Z",
    fnolChannel: "web_form",
    documentStatus: "complete",
    reviewGate: "adjuster_review",
    triageLane: "standard",
    triageSignals: ["complete_evidence"],
    adverseActionNoticeRequired: false,
    governanceCheckpoint: {
      ownerRole: "adjuster",
      dueAt: "2026-06-02T17:00:00Z",
      nextAction: "Send payout confirmation and close the evidence packet after the recovery window expires.",
    },
    communicationCheckpoint: {
      audience: "customer",
      channel: "customer_portal",
      status: "sent",
      lastSentAt: "2026-06-01T17:05:00Z",
      message: "Customer payout confirmation was sent after the recovery window closed and the evidence packet was archived.",
    },
    complianceCheckpoint: {
      jurisdiction: "CA",
      obligation: "settlement_payment",
      status: "due",
      dueAt: "2026-06-04T17:00:00Z",
      ruleReference: "Carrier-configured California settlement payment diary",
    },
    aiDecisionRationale: "Theft payout cleared after police report, policy status, and recovery attempts support the covered loss amount.",
    evidenceAnchors: [
      { label: "Vehicle theft police report", sourceType: "police_report", receivedAt: "2026-04-30T13:05:00Z" },
      { label: "Active policy and deductible confirmation", sourceType: "policy_record", receivedAt: "2026-05-01T09:00:00Z" },
    ],
    evidenceRequirements: [
      { label: "Vehicle theft police report", status: "received", ownerRole: "adjuster" },
      { label: "Active policy and deductible confirmation", status: "received", ownerRole: "adjuster" },
      { label: "Recovery window search log", status: "received", ownerRole: "adjuster" },
    ],
    aiFraudScore: 5,
    adjuster: "Maria Gonzalez",
    notes: "Vehicle stolen from secured parking. Police report filed. GPS recovery unsuccessful. Payout processing.",
  },
  {
    id: "clm_004",
    claimNumber: "CLM-2026-0512",
    policyId: "pol_004",
    customerId: "cust_004",
    type: "commercial_liability",
    status: "paid",
    amount: 32000,
    deductibleApplied: 10000,
    payoutAmount: 22000,
    reserveAmount: 35000,
    filedDate: "2026-03-18T10:45:00Z",
    lastUpdated: "2026-05-10T14:00:00Z",
    fnolChannel: "call_center",
    documentStatus: "complete",
    reviewGate: "legal_review",
    triageLane: "specialist_review",
    triageSignals: ["legal_exposure"],
    adverseActionNoticeRequired: false,
    governanceCheckpoint: {
      ownerRole: "legal",
      dueAt: "2026-05-17T17:00:00Z",
      nextAction: "File the premises-safety follow-up note against the liability loss-control record.",
    },
    communicationCheckpoint: {
      audience: "customer",
      channel: "sms",
      status: "sent",
      lastSentAt: "2026-05-10T15:30:00Z",
      message: "Settlement closure notice was sent after legal confirmed premises-safety follow-up was filed.",
    },
    complianceCheckpoint: {
      jurisdiction: "TX",
      obligation: "settlement_payment",
      status: "met",
      dueAt: "2026-05-12T17:00:00Z",
      completedAt: "2026-05-10T14:00:00Z",
      ruleReference: "Carrier-configured Texas settlement payment diary",
    },
    aiDecisionRationale: "Liability settlement required legal review because medical bills and premises inspection findings drove the payout recommendation.",
    evidenceAnchors: [
      { label: "Medical bill packet", sourceType: "medical_bill", receivedAt: "2026-04-02T15:30:00Z" },
      { label: "Customer incident statement", sourceType: "customer_statement", receivedAt: "2026-03-18T11:20:00Z" },
    ],
    evidenceRequirements: [
      { label: "Medical bill packet", status: "received", ownerRole: "legal" },
      { label: "Customer incident statement", status: "received", ownerRole: "legal" },
      { label: "Premises safety inspection", status: "received", ownerRole: "adjuster" },
    ],
    aiFraudScore: 22,
    adjuster: "Jennifer Wu",
    notes: "Customer slip-and-fall on premises. Medical bills and settlement paid. Safety inspection scheduled.",
  },
  {
    id: "clm_005",
    claimNumber: "CLM-2026-0428",
    policyId: "pol_002",
    customerId: "cust_001",
    type: "home_theft",
    status: "paid",
    amount: 18000,
    deductibleApplied: 2500,
    payoutAmount: 15500,
    reserveAmount: 16000,
    filedDate: "2026-03-02T20:00:00Z",
    lastUpdated: "2026-04-15T09:30:00Z",
    fnolChannel: "mobile_app",
    documentStatus: "complete",
    reviewGate: "adjuster_review",
    triageLane: "standard",
    triageSignals: ["complete_evidence"],
    adverseActionNoticeRequired: false,
    governanceCheckpoint: {
      ownerRole: "adjuster",
      dueAt: "2026-04-16T17:00:00Z",
      nextAction: "Archive police report and item-photo evidence with the scheduled-property settlement worksheet.",
    },
    communicationCheckpoint: {
      audience: "customer",
      channel: "customer_portal",
      status: "sent",
      lastSentAt: "2026-04-15T10:45:00Z",
      message: "Customer settlement update was sent with the scheduled-property worksheet archived for claim history visibility.",
    },
    complianceCheckpoint: {
      jurisdiction: "CA",
      obligation: "settlement_payment",
      status: "met",
      dueAt: "2026-04-18T17:00:00Z",
      completedAt: "2026-04-15T09:30:00Z",
      ruleReference: "Carrier-configured California settlement payment diary",
    },
    aiDecisionRationale: "Home theft claim paid after police report and item photos supported the scheduled personal-property loss.",
    evidenceAnchors: [
      { label: "Police burglary report", sourceType: "police_report", receivedAt: "2026-03-03T08:30:00Z" },
      { label: "Customer-uploaded property photos", sourceType: "photos", receivedAt: "2026-03-02T20:18:00Z" },
    ],
    evidenceRequirements: [
      { label: "Police burglary report", status: "received", ownerRole: "adjuster" },
      { label: "Customer-uploaded property photos", status: "received", ownerRole: "adjuster" },
      { label: "Scheduled-property settlement worksheet", status: "received", ownerRole: "adjuster" },
    ],
    aiFraudScore: 9,
    adjuster: "Robert Kim",
    notes: "Break-in through rear window. Electronics and jewelry taken. Police report on file. Payout sent.",
  },
  {
    id: "clm_006",
    claimNumber: "CLM-2026-0395",
    policyId: "pol_001",
    customerId: "cust_001",
    type: "auto_collision",
    status: "denied",
    amount: 7800,
    deductibleApplied: 1000,
    payoutAmount: 0,
    reserveAmount: 7300,
    filedDate: "2026-02-10T07:30:00Z",
    lastUpdated: "2026-03-01T12:00:00Z",
    fnolChannel: "call_center",
    documentStatus: "needs_review",
    reviewGate: "supervisor_review",
    triageLane: "specialist_review",
    triageSignals: ["high_fraud_score", "coverage_dispute", "adverse_action_risk"],
    adverseActionNoticeRequired: true,
    governanceCheckpoint: {
      ownerRole: "supervisor",
      dueAt: "2026-03-02T17:00:00Z",
      nextAction: "Supervisor validates adverse-action notice language against policy-lapse evidence before customer notice.",
    },
    communicationCheckpoint: {
      audience: "customer",
      channel: "customer_portal",
      status: "scheduled",
      lastSentAt: "2026-02-28T09:00:00Z",
      nextDueAt: "2026-03-02T17:30:00Z",
      message: "Customer notice remains scheduled until supervisor validates policy-lapse evidence and adverse-action language.",
    },
    complianceCheckpoint: {
      jurisdiction: "CA",
      obligation: "decision_notice",
      status: "at_risk",
      dueAt: "2026-03-02T18:00:00Z",
      ruleReference: "Carrier-configured California coverage decision notice diary",
    },
    claimantReviewCheckpoint: {
      status: "pending_notice",
      reviewerRole: "supervisor",
      requestChannels: ["customer_portal", "claims_phone", "written_request"],
      decisionBasisSummary:
        "Policy-lapse timeline and statement variance require human reconsideration before any denial is upheld.",
      ruleReference: "Carrier-configured California claim reconsideration workflow",
    },
    aiDecisionRationale: "Potential adverse claim decision is routed to supervisor review because policy records show a coverage gap and statements conflict.",
    evidenceAnchors: [
      { label: "Policy lapse timeline", sourceType: "policy_record", receivedAt: "2026-02-10T08:05:00Z" },
      { label: "Recorded customer statement variance", sourceType: "customer_statement", receivedAt: "2026-02-11T10:40:00Z" },
    ],
    evidenceRequirements: [
      { label: "Policy lapse timeline", status: "received", ownerRole: "supervisor" },
      { label: "Recorded customer statement variance", status: "received", ownerRole: "supervisor" },
      {
        label: "Coverage denial notice language",
        status: "needs_adjuster_review",
        ownerRole: "supervisor",
        dueAt: "2026-03-02T17:00:00Z",
      },
    ],
    aiFraudScore: 87,
    adjuster: "Jennifer Wu",
    notes: "Denied: policy not in force at time of incident. Coverage gap identified. Fraud indicators: inconsistent statements.",
  },
];

export const demoRiskAssessments: RiskAssessment[] = [
  {
    customerId: "cust_001",
    overallScore: 16,
    level: "low",
    factors: [
      { name: "Claims Frequency", score: 12, weight: 0.3, description: "1 claim in 8 years" },
      { name: "Payment History", score: 5, weight: 0.25, description: "Zero late payments" },
      { name: "Property Location", score: 40, weight: 0.2, description: "Earthquake zone, mitigated" },
      { name: "Credit Score", score: 8, weight: 0.15, description: "Excellent credit" },
      { name: "Coverage Ratio", score: 15, weight: 0.1, description: "Well-insured assets" },
    ],
    lastAssessed: "2026-06-01T00:00:00Z",
  },
  {
    customerId: "cust_004",
    overallScore: 62,
    level: "elevated",
    factors: [
      { name: "Claims Frequency", score: 78, weight: 0.3, description: "3 claims in 5 years" },
      { name: "Payment History", score: 45, weight: 0.25, description: "2 late payments in 12 months" },
      { name: "Business Type", score: 70, weight: 0.25, description: "Restaurant with liquor service" },
      { name: "Credit Score", score: 55, weight: 0.2, description: "Fair credit" },
    ],
    lastAssessed: "2026-05-15T00:00:00Z",
  },
  {
    customerId: "cust_006",
    overallScore: 81,
    level: "high",
    factors: [
      { name: "Claims Frequency", score: 92, weight: 0.35, description: "4 claims in 4 years" },
      { name: "Payment History", score: 75, weight: 0.25, description: "4 late payments, 1 missed" },
      { name: "Policy Tenure", score: 60, weight: 0.2, description: "Short tenure, frequent shopping" },
      { name: "Credit Score", score: 85, weight: 0.2, description: "Poor credit" },
    ],
    lastAssessed: "2026-06-05T00:00:00Z",
  },
];

export const demoClaimsPipeline: ClaimsPipelineStage[] = [
  { id: "stage_new", name: "New", order: 1, claimCount: 1, totalAmount: 12500 },
  { id: "stage_review", name: "Under Review", order: 2, claimCount: 1, totalAmount: 85000 },
  { id: "stage_approved", name: "Approved", order: 3, claimCount: 1, totalAmount: 42000 },
  { id: "stage_paid", name: "Paid", order: 4, claimCount: 2, totalAmount: 50000 },
  { id: "stage_denied", name: "Denied", order: 5, claimCount: 1, totalAmount: 7800 },
];

export const demoAgencyMetrics: AgencyMetrics = {
  activePolicies: 8,
  policiesExpiring30d: 2,
  claimsOpen: 2,
  claimsPaidThisMonth: 2,
  monthlyPremiumVolume: 6672,
  annualPremiumVolume: 80064,
  avgPolicyValue: 2143750,
  avgRiskScore: 28,
  avgClaimResolutionDays: 32,
  fraudDetectionRate: 91,
  customerRetentionRate: 94,
  npsScore: 72,
};
